                                                                                                                                                                                                                                                                                                                                                                                -- Diagnose Teams Table Structure
                                                                                                                                                                                                                                                                                                                                                                                -- Run this to see what columns you currently have

                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                -- 1. Check if teams table exists
                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                    CASE 
                                                                                                                                                                                                                                                                                                                                                                                        WHEN EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                            SELECT 1 FROM information_schema.tables 
                                                                                                                                                                                                                                                                                                                                                                                            WHERE table_schema = 'public' AND table_name = 'teams'
                                                                                                                                                                                                                                                                                                                                                                                        ) 
                                                                                                                                                                                                                                                                                                                                                                                        THEN '✅ teams table EXISTS'
                                                                                                                                                                                                                                                                                                                                                                                        ELSE '❌ teams table DOES NOT EXIST'
                                                                                                                                                                                                                                                                                                                                                                                    END as table_status;

                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                -- 2. Show all current columns
                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                    column_name, 
                                                                                                                                                                                                                                                                                                                                                                                    data_type,
                                                                                                                                                                                                                                                                                                                                                                                    character_maximum_length,
                                                                                                                                                                                                                                                                                                                                                                                    is_nullable,
                                                                                                                                                                                                                                                                                                                                                                                    column_default
                                                                                                                                                                                                                                                                                                                                                                                FROM information_schema.columns
                                                                                                                                                                                                                                                                                                                                                                                WHERE table_schema = 'public' 
                                                                                                                                                                                                                                                                                                                                                                                AND table_name = 'teams'
                                                                                                                                                                                                                                                                                                                                                                                ORDER BY ordinal_position;

                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                -- 3. Check for missing columns
                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                WITH required_columns AS (
                                                                                                                                                                                                                                                                                                                                                                                    SELECT unnest(ARRAY[
                                                                                                                                                                                                                                                                                                                                                                                        'id', 'name', 'crest_url', 'captain', 'formation',
                                                                                                                                                                                                                                                                                                                                                                                        'played', 'won', 'drawn', 'lost', 
                                                                                                                                                                                                                                                                                                                                                                                        'goals_for', 'goals_against', 'points',
                                                                                                                                                                                                                                                                                                                                                                                        'group_name', 'category', 'registration_id',
                                                                                                                                                                                                                                                                                                                                                                                        'created_at', 'updated_at'
                                                                                                                                                                                                                                                                                                                                                                                    ]) AS column_name
                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                existing_columns AS (
                                                                                                                                                                                                                                                                                                                                                                                    SELECT column_name
                                                                                                                                                                                                                                                                                                                                                                                    FROM information_schema.columns
                                                                                                                                                                                                                                                                                                                                                                                    WHERE table_schema = 'public' 
                                                                                                                                                                                                                                                                                                                                                                                    AND table_name = 'teams'
                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                    rc.column_name,
                                                                                                                                                                                                                                                                                                                                                                                    CASE 
                                                                                                                                                                                                                                                                                                                                                                                        WHEN ec.column_name IS NOT NULL THEN '✅ EXISTS'
                                                                                                                                                                                                                                                                                                                                                                                        ELSE '❌ MISSING'
                                                                                                                                                                                                                                                                                                                                                                                    END as status
                                                                                                                                                                                                                                                                                                                                                                                FROM required_columns rc
                                                                                                                                                                                                                                                                                                                                                                                LEFT JOIN existing_columns ec ON rc.column_name = ec.column_name
                                                                                                                                                                                                                                                                                                                                                                                ORDER BY 
                                                                                                                                                                                                                                                                                                                                                                                    CASE WHEN ec.column_name IS NULL THEN 0 ELSE 1 END,
                                                                                                                                                                                                                                                                                                                                                                                    rc.column_name;

                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                -- 4. Show sample data (if any)
                                                                                                                                                                                                                                                                                                                                                                                -- ============================================
                                                                                                                                                                                                                                                                                                                                                                                SELECT 
                                                                                                                                                                                                                                                                                                                                                                                    COUNT(*) as total_teams,
                                                                                                                                                                                                                                                                                                                                                                                    COUNT(DISTINCT category) as categories_count,
                                                                                                                                                                                                                                                                                                                                                                                    string_agg(DISTINCT category, ', ') as categories
                                                                                                                                                                                                                                                                                                                                                                                FROM teams;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
