name: Periodic Site Refresh

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MUQAWAMA }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ github.repository_owner }}/sio-afe.github.io/dispatches" \
            -d '{"event_type":"pages_build"}'
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.MUQAWAMA }} 